#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

autorandr --change
setbg &			                            # set the background with the `setbg` script
setxkbmap "us_intl,ru" "altgr-intl,"        # Add russian layout to keyboard
redshift -l 52.37:4.89 -r &                    # set color temperature of display according to time of day
xset r rate 300 50 &	                    # Speed xrate up
unclutter &		                            # Remove mouse when idle
picom -b --experimental-backends            # picom for transparency
#flameshot &                                 # Screenshot daemon
transmission-daemon &
nm-applet &
#xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config
claws-mail --alternate-config-dir "$XDG_DATA_HOME"/claws-mail &


xrdb -load "$HOME/.config/x11/xresources"
